-- ====================================================================
-- PAAVAI BLOODCONNECT - SUPABASE POSTGRESQL DATABASE INITIALIZATION SCRIPT
-- Copy and run this script in your Supabase SQL Editor:
-- https://supabase.com -> Project -> SQL Editor -> New Query
-- ====================================================================

-- 0. GRANT CREATE PRIVILEGES ON THE PUBLIC SCHEMA (Resolves PG15+ Permission Denied errors)
-- In modern Supabase instances (PostgreSQL 15+), the default permissions of the `public` schema has CREATE revoked for the public.
-- To ensure the `postgres` administrator role has explicit permissions to create tables, we grant USAGE and CREATE:
GRANT USAGE ON SCHEMA public TO postgres;
GRANT CREATE ON SCHEMA public TO postgres;

-- Restore standard schema-level permissions of the public schema to essential database roles
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;
GRANT ALL ON SCHEMA public TO public;

-- Ensure default privileges are correctly granted for any new resources created hereafter
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres, anon, authenticated, service_role;

-- ==========================================
-- 2. CREATE `donors` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS donors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  "registerNumber" TEXT UNIQUE NOT NULL, -- Keep camelCase to map Room/Moshi entities safely
  department TEXT NOT NULL,
  year TEXT NOT NULL,
  "bloodGroup" TEXT NOT NULL,
  "mobileNumber" TEXT NOT NULL,
  email TEXT NOT NULL,
  location TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL,
  "lastDonationDate" TEXT NOT NULL,
  "userType" TEXT NOT NULL DEFAULT 'Student',
  availability BOOLEAN NOT NULL DEFAULT true,
  "totalDonations" INTEGER NOT NULL DEFAULT 0,
  gender TEXT NOT NULL DEFAULT 'Male',
  dob TEXT NOT NULL DEFAULT '2005-01-01',
  address TEXT NOT NULL DEFAULT 'Namakkal, Tamil Nadu',
  "emergencyContact" TEXT NOT NULL DEFAULT '+91 9900998877',
  "profilePhoto" TEXT NOT NULL DEFAULT ''
);

-- ==========================================
-- 3. CREATE `blood_requests` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS blood_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bloodGroup" TEXT NOT NULL,
  "unitsRequired" INTEGER NOT NULL,
  "hospitalName" TEXT NOT NULL,
  "patientName" TEXT NOT NULL,
  "urgencyLevel" TEXT NOT NULL,
  "contactName" TEXT NOT NULL,
  "contactNumber" TEXT NOT NULL,
  timestamp BIGINT NOT NULL,
  "isFulfilled" BOOLEAN NOT NULL DEFAULT false,
  "simulatedAlertsSent" BOOLEAN NOT NULL DEFAULT false
);

-- ==========================================
-- 4. CREATE `donation_camps` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS donation_camps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  venue TEXT NOT NULL,
  "Description" TEXT NOT NULL,
  "registeredCount" INTEGER NOT NULL DEFAULT 0
);

-- ==========================================
-- 5. CREATE `donation_history` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS donation_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "donorName" TEXT NOT NULL,
  "donorRegisterNumber" TEXT NOT NULL,
  date TEXT NOT NULL,
  "bloodGroup" TEXT NOT NULL,
  "unitsDonated" INTEGER NOT NULL DEFAULT 1,
  "hospitalName" TEXT NOT NULL DEFAULT 'Paavai Blood Camp'
);

-- ==========================================
-- 6. CREATE `user_accounts` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS user_accounts (
  email TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  "registerNumber" TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL,
  year TEXT NOT NULL,
  "bloodGroup" TEXT NOT NULL,
  phone TEXT NOT NULL
);

-- ==========================================
-- Enable RLS on all tables
ALTER TABLE donors ENABLE ROW LEVEL SECURITY;
ALTER TABLE blood_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE donation_camps ENABLE ROW LEVEL SECURITY;
ALTER TABLE donation_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_accounts ENABLE ROW LEVEL SECURITY;

-- User Accounts: Users can only read all, but update their own
CREATE POLICY "Enable read access for all users" ON "public"."user_accounts" FOR SELECT USING (true);
CREATE POLICY "Users can insert their own account" ON "public"."user_accounts" FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update their own account" ON "public"."user_accounts" 
  FOR UPDATE USING (email = auth.email()) WITH CHECK (email = auth.email());

-- Donors: Donors can read all donors (for finding matches), but only update themselves
CREATE POLICY "Enable read access for all users" ON "public"."donors" FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON "public"."donors" FOR INSERT WITH CHECK (true);
CREATE POLICY "Donors can only update their own profile" ON "public"."donors" 
  FOR UPDATE USING (
    (SELECT email FROM user_accounts WHERE "registerNumber" = donors."registerNumber") = auth.email() 
    OR auth.role() = 'service_role'
  );

-- Blood Requests: Anyone can read, Requesters can insert/update their own, Admins can update any
CREATE POLICY "Enable read access for all users" ON "public"."blood_requests" FOR SELECT USING (true);
CREATE POLICY "Users can insert requests" ON "public"."blood_requests" FOR INSERT WITH CHECK (true);
CREATE POLICY "Requesters can update their own requests" ON "public"."blood_requests" 
  FOR UPDATE USING (
    "contactNumber" = (SELECT phone FROM user_accounts WHERE email = auth.email()) 
    OR auth.role() = 'service_role'
  );

-- Donation Camps: Public read, Admin only write (requires admin role check in user_accounts)
CREATE POLICY "Allow public read access" ON donation_camps FOR SELECT USING (true);
CREATE POLICY "Allow Admin insert access" ON donation_camps FOR INSERT WITH CHECK (
  (SELECT role FROM user_accounts WHERE email = auth.email()) = 'Admin' OR auth.role() = 'service_role'
);
CREATE POLICY "Allow Admin update access" ON donation_camps FOR UPDATE USING (
  (SELECT role FROM user_accounts WHERE email = auth.email()) = 'Admin' OR auth.role() = 'service_role'
);
-- Add Volunteer and Admin update policy for blood_requests
CREATE POLICY "Volunteers and Admins can update requests" ON "public"."blood_requests"
  FOR UPDATE USING (
    (SELECT role FROM user_accounts WHERE email = auth.email()) IN ('Admin', 'Volunteer', 'NSS Volunteer', 'NCC Volunteer', 'YRC Volunteer')
    OR auth.role() = 'service_role'
  );
