-- ====================================================================
-- PAAVAI BLOODCONNECT - SUPABASE POSTGRESQL DATABASE INITIALIZATION SCRIPT
-- Copy and run this script in your Supabase SQL Editor:
-- https://supabase.com -> Project -> SQL Editor -> New Query
-- ====================================================================

-- 0. GRANT CREATE PRIVILEGES ON THE PUBLIC SCHEMA (Resolves PG15+ Permission Denied errors)
-- In modern Supabase instances (PostgreSQL 15+), the default permissions of the `public` schema has CREATE revoked for the public.
-- To ensure the `postgres` administrator role has explicit permissions to create tables, we grant USAGE and CREATE:
GRANT USAGE ON SCHEMA public TO postgres;
GRANT CREATE ON SCHEMA public TO postgres;

-- Restore standard schema-level permissions of the public schema to essential database roles
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;
GRANT ALL ON SCHEMA public TO public;

-- Ensure default privileges are correctly granted for any new resources created hereafter
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres, anon, authenticated, service_role;

-- ==========================================
-- 2. CREATE `donors` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS donors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  "registerNumber" TEXT UNIQUE NOT NULL, -- Keep camelCase to map Room/Moshi entities safely
  department TEXT NOT NULL,
  year TEXT NOT NULL,
  "bloodGroup" TEXT NOT NULL,
  "mobileNumber" TEXT NOT NULL,
  email TEXT NOT NULL,
  location TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL,
  "lastDonationDate" TEXT NOT NULL,
  "userType" TEXT NOT NULL DEFAULT 'Student',
  availability BOOLEAN NOT NULL DEFAULT true,
  "totalDonations" INTEGER NOT NULL DEFAULT 0,
  gender TEXT NOT NULL DEFAULT 'Male',
  dob TEXT NOT NULL DEFAULT '2005-01-01',
  address TEXT NOT NULL DEFAULT 'Namakkal, Tamil Nadu',
  "emergencyContact" TEXT NOT NULL DEFAULT '+91 9900998877',
  "profilePhoto" TEXT NOT NULL DEFAULT ''
);

-- ==========================================
-- 3. CREATE `blood_requests` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS blood_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bloodGroup" TEXT NOT NULL,
  "unitsRequired" INTEGER NOT NULL,
  "hospitalName" TEXT NOT NULL,
  "patientName" TEXT NOT NULL,
  "urgencyLevel" TEXT NOT NULL,
  "contactName" TEXT NOT NULL,
  "contactNumber" TEXT NOT NULL,
  timestamp BIGINT NOT NULL,
  "isFulfilled" BOOLEAN NOT NULL DEFAULT false,
  "simulatedAlertsSent" BOOLEAN NOT NULL DEFAULT false
);

-- ==========================================
-- 4. CREATE `donation_camps` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS donation_camps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  venue TEXT NOT NULL,
  "Description" TEXT NOT NULL,
  "registeredCount" INTEGER NOT NULL DEFAULT 0
);

-- ==========================================
-- 5. CREATE `donation_history` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS donation_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "donorName" TEXT NOT NULL,
  "donorRegisterNumber" TEXT NOT NULL,
  date TEXT NOT NULL,
  "bloodGroup" TEXT NOT NULL,
  "unitsDonated" INTEGER NOT NULL DEFAULT 1,
  "hospitalName" TEXT NOT NULL DEFAULT 'Paavai Blood Camp'
);

-- ==========================================
-- 6. CREATE `user_accounts` TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS user_accounts (
  email TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  "registerNumber" TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL,
  year TEXT NOT NULL,
  "bloodGroup" TEXT NOT NULL,
  phone TEXT NOT NULL
);

-- ==========================================
-- 7. SECURITY & ROW LEVEL SECURITY (RLS)
-- To enable easy API access with your public client Key (anon key), 
-- you can temporarily disable RLS, or add standard public permissive policies.
-- ==========================================

ALTER TABLE donors DISABLE ROW LEVEL SECURITY;
ALTER TABLE blood_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE donation_camps DISABLE ROW LEVEL SECURITY;
ALTER TABLE donation_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_accounts DISABLE ROW LEVEL SECURITY;

-- If you prefer keeping RLS enabled on Supabase, select 'Enable RLS' on those tables
-- and execute the following public insert/select/update permissive billing policies:
/*
CREATE POLICY "Allow public read access" ON donors FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON donors FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON donors FOR UPDATE USING (true);

CREATE POLICY "Allow public read access" ON blood_requests FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON blood_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON blood_requests FOR UPDATE USING (true);

CREATE POLICY "Allow public read access" ON donation_camps FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON donation_camps FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON donation_camps FOR UPDATE USING (true);

CREATE POLICY "Allow public read access" ON donation_history FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON donation_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON donation_history FOR UPDATE USING (true);
*/
